DROP DATABASE IF EXISTS `CONSUMER_REVIEWS`;
CREATE DATABASE `CONSUMER_REVIEWS`;
USE `CONSUMER_REVIEWS`;

DROP TABLE IF EXISTS `BIZRATE_AFTER_PURCHASE_RATINGS`;
DROP TABLE IF EXISTS `BIZRATE_SITE_EXPERIENCE_RATINGS`;
DROP TABLE IF EXISTS `BIZRATE_REVIEW`;
CREATE TABLE `BIZRATE_REVIEW` (
  `PID` BIGINT AUTO_INCREMENT,
  `CREATE_TIME` DATETIME,
  `SOURCE` VARCHAR(128),
  `STORE` VARCHAR(128),
  `SHOP_AGAIN` INT NULL DEFAULT NULL,
  `TO_RECOMMEND` INT NULL DEFAULT NULL,
  `SATISFACTION` INT NULL DEFAULT NULL,
  `BEFORE_AUTHOR` VARCHAR(256),
  `BEFORE_DATE` DATE NULL DEFAULT NULL,
  `BEFORE_REVIEW` TEXT,
  `AFTER_AUTHOR` VARCHAR(256),
  `AFTER_DATE` DATE NULL DEFAULT NULL,
  `AFTER_REVIEW` TEXT,
  PRIMARY KEY (`PID`)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

CREATE INDEX `IX__BIZRATE_REVIEW_STORE` ON BIZRATE_REVIEW(`STORE`);

CREATE TABLE `BIZRATE_SITE_EXPERIENCE_RATINGS` (
  `PID` BIGINT AUTO_INCREMENT,
  `CREATE_TIME` DATETIME,
  `FK_REVIEW_PID` BIGINT,
  `SHIPPING_OPTIONS` INT NULL DEFAULT NULL,
  `SHIPPING_CHARGES` INT NULL DEFAULT NULL,
  `EASE_OF_FINDING` INT NULL DEFAULT NULL,
  `PRICE_RELATIVE_TO_OTHER` INT NULL DEFAULT NULL,
  `CLARITY_PRODUCT_INFO` INT NULL DEFAULT NULL,
  `CHARGES_STATED_CLEARLY` INT NULL DEFAULT NULL,
  `SITE_DESIGN` INT NULL DEFAULT NULL,
  `PRODUCT_SELECTION` INT NULL DEFAULT NULL,
  `CHECKOUT_SATISFACTION` INT NULL DEFAULT NULL,
  PRIMARY KEY (`PID`),
  CONSTRAINT `FK__SITE_EXPERIENCE__REVIEW` FOREIGN KEY (`FK_REVIEW_PID`) REFERENCES `BIZRATE_REVIEW`(`PID`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT
);

CREATE TABLE `BIZRATE_AFTER_PURCHASE_RATINGS` (
  `PID` BIGINT AUTO_INCREMENT,
  `CREATE_TIME` DATETIME,
  `FK_REVIEW_PID` BIGINT,
  `PRODUCT_AVAILABILITY` INT NULL DEFAULT NULL,
  `ONTIME_DELIVERY` INT NULL DEFAULT NULL,
  `PRODUCT_MET_EXPECTATIONS` INT NULL DEFAULT NULL,
  `ORDER_TRACKING` INT NULL DEFAULT NULL,
  `RETURN_PROCESS` INT NULL DEFAULT NULL,
  `CUSTOMER_SUPPORT` INT NULL DEFAULT NULL,
  PRIMARY KEY (`PID`),
  CONSTRAINT `FK__AFTER_PURCHASE__REVIEW` FOREIGN KEY (`FK_REVIEW_PID`) REFERENCES `BIZRATE_REVIEW`(`PID`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT
);
