version: "3.6"

services:
  postgres:
    image: lkhoho/postgres:latest
    ports:
      - 5432:5432
    volumes:
      - $DOCKER_DATA_ROOT/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=welcome

  mongodb:
    image: lkhoho/mongodb:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=welcome
    ports:
      - 27017:27017
      - 28017:28017
    volumes:
      - $DOCKER_DATA_ROOT/mongodb:/data/db
