ALTER TABLE `CONSUMER_REVIEWS`.`BIZRATE_REVIEW` MODIFY `BEFORE_REVIEW` TEXT;
ALTER TABLE `CONSUMER_REVIEWS`.`BIZRATE_REVIEW` MODIFY `AFTER_REVIEW` TEXT;

DROP TABLE IF EXISTS `CONSUMER_REVIEWS`.`KBB_RATINGS`;
DROP TABLE IF EXISTS `CONSUMER_REVIEWS`.`KBB_REVIEW`;

CREATE TABLE `CONSUMER_REVIEWS`.`KBB_REVIEW` (
  `PID` BIGINT AUTO_INCREMENT,
  `CREATE_TIME` DATETIME,
  `SOURCE` VARCHAR(128),
  `YEAR` VARCHAR(128),
  `MAKE` VARCHAR(128),
  `MODEL` VARCHAR(128),
  `MILEAGE` INT NULL DEFAULT NULL,
  `NUM_RECOMMEND` INT NULL DEFAULT NULL,
  `NUM_RECOMMEND_OUT_OF` INT NULL DEFAULT NULL,
  `NUM_HELPFUL` INT NULL DEFAULT NULL,
  `NUM_HELPFUL_OUT_OF` INT NULL DEFAULT NULL,
  `AUTHOR` VARCHAR(256),
  `TITLE` VARCHAR(256),
  `DATE` DATE NULL DEFAULT NULL,
  `REVIEW` TEXT,
  `PROS` VARCHAR(256),
  `CONS` VARCHAR(256),
  PRIMARY KEY (`PID`),
  INDEX `IX__KBB_REVIEW__YEAR_MAKE_MODEL` (`YEAR`, `MAKE`, `MODEL`)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

CREATE TABLE `CONSUMER_REVIEWS`.`KBB_RATINGS`(
  `PID` BIGINT AUTO_INCREMENT,
  `CREATE_TIME` DATETIME,
  `FK_REVIEW_PID` BIGINT,
  `OVERALL` INT NULL DEFAULT NULL,
  `VALUE` INT NULL DEFAULT NULL,
  `RELIABILITY` INT NULL DEFAULT NULL,
  `COMFORT` INT NULL DEFAULT NULL,
  `STYLING` INT NULL DEFAULT NULL,
  `QUALITY` INT NULL DEFAULT NULL,
  `PERFORMANCE` INT NULL DEFAULT NULL,
  PRIMARY KEY (`PID`),
  CONSTRAINT `FK__RATINGS__REVIEW` FOREIGN KEY (`FK_REVIEW_PID`) REFERENCES `CONSUMER_REVIEWS`.`KBB_REVIEW`(`PID`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT
);
